apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlaas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rlaas
  template:
    metadata:
      labels:
        app: rlaas
    spec:
      containers:
      - name: rlaas
        image: rlaas-rlaas:latest
        imagePullPolicy: Never   # use local image, don't pull from Docker Hub
        ports:
        - containerPort: 50051
        - containerPort: 8090
        env:
        - name: REDIS_ADDR
          value: redis:6379
        - name: DATABASE_URL
          value: postgresql://rlaas:rlaas@postgres:5432/rlaas
        livenessProbe:
          httpGet:
            path: /rules
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: rlaas
spec:
  type: LoadBalancer
  selector:
    app: rlaas
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: admin
    port: 8090
    targetPort: 8090